### ISSUE TITLE
CSV files

### ISSUE THREAD

**Issue by dhruvmsheth** [mikedsp/machine-learning-in-healthcare#1]
You haven't uploaded the CSV files and it's not possible to carry out the prediction model further. Can you pls upload the CSV files

**Comment by mikedsp** [comment]
Hi Dhruv,I am not sure which csv files you are referring to. For all the projects except 1, the data was pulled directly from an online repository. The URL of the repository is in my Jupyter notebooks code. For one of the projects, the data was no longer in the online repository, but I managed to find a repository in Github where someone had archived a copy of the data. I did not put that in my repository because the comment in the online repository was that the group that had shared the data no longer wished to share it. If that is the data you are looking for, try doing a search on Github. 
Regards,Mike


    On Friday, August 28, 2020, 12:22:22 AM EDT, Dhruv Sheth <notifications@github.com> wrote:  
 
 


You haven't uploaded the CSV files and it's not possible to carry out the prediction model further. Can you pls upload the CSV files

**Comment by dhruvmsheth** [comment]
Oh ok thank you so much
